version: '3'
services:
  predict:
    build: ./predict-service/
    ports:
      - "8092:8092"

  weather:
    build: ./weather-service/
    ports:
      - "8091:8091"
    depends_on:
      - postgres

  rbc:
    build: ./rbc-service/
    ports:
      - "8093:8093"


  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=alena
      - POSTGRES_PASSWORD=alena
      - POSTGRES_NAME=alena
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mydomain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"