version: '3'
services:
  predict:
    build: ./predict-service/
    ports:
      - "8092:8092"

  weather:
    build: ./weather-service/
    ports:
      - "8091:8091"

  rbc:
    build: ./rbc-service/
    ports:
      - "8093:8093"