global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'weather_micrometer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['weather:8091']
  - job_name: 'rbc_micrometer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['rbc:8093']
  - job_name: 'predict_micrometer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['predict:8092']