apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      name: weather
      labels:
        app: weather
    spec:
      containers:
        - name: weather
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_password
          image: weather
          imagePullPolicy: IfNotPresent